; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27031.1 

	TITLE	C:\Users\ntrembla71\Desktop\raven_VS2015\VS2015\Buckland_Chapter7 to 10_Raven\goals\Goal_SayPhrase.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMTD
INCLUDELIB OLDNAMES

END
